-- Phase 6: Gestão financeira escolar. Execute in Neon after previous migrations.
CREATE TABLE IF NOT EXISTS finance_category (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, name text NOT NULL, description text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS finance_category_school_name_uq ON finance_category(school_id, name);
CREATE TABLE IF NOT EXISTS finance_charge_type (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, category_id uuid REFERENCES finance_category(id) ON DELETE SET NULL, name text NOT NULL, description text, default_amount numeric(12,2) NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS finance_charge_type_school_name_uq ON finance_charge_type(school_id, name);
CREATE TABLE IF NOT EXISTS payment_plan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, name text NOT NULL, description text, installments integer NOT NULL DEFAULT 1, due_day integer NOT NULL DEFAULT 10, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS student_payment_plan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES student(id) ON DELETE CASCADE, plan_id uuid NOT NULL REFERENCES payment_plan(id) ON DELETE RESTRICT, starts_on date NOT NULL, ends_on date, status text NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS finance_invoice (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES student(id) ON DELETE RESTRICT, plan_assignment_id uuid REFERENCES student_payment_plan(id) ON DELETE SET NULL, reference text NOT NULL, due_on date NOT NULL, total_amount numeric(12,2) NOT NULL, status text NOT NULL DEFAULT 'OPEN', description text, created_by text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), cancelled_at timestamptz);
CREATE TABLE IF NOT EXISTS finance_charge (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, invoice_id uuid NOT NULL REFERENCES finance_invoice(id) ON DELETE CASCADE, charge_type_id uuid REFERENCES finance_charge_type(id) ON DELETE SET NULL, description text NOT NULL, amount numeric(12,2) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payment_settlement (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, invoice_id uuid NOT NULL REFERENCES finance_invoice(id) ON DELETE RESTRICT, amount numeric(12,2) NOT NULL, paid_on date NOT NULL, method text NOT NULL, retroactive_justification text, cancelled_at timestamptz, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS finance_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES school(id) ON DELETE CASCADE, entity_type text NOT NULL, entity_id uuid, action text NOT NULL, justification text, before_data jsonb, after_data jsonb, actor_user_id text, created_at timestamptz NOT NULL DEFAULT now());
